version: '3.3'
services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - 6379
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - ./docker/redis/data:/var/lib/redis
      - ./docker/redis/redis.conf:/etc/redis/redis.conf